all:
  vars:
    ansible_connection: ssh
    ansible_user: ubuntu
    ansible_become: true
    ansible_ssh_private_key_file: key.pem
    ansible_ssh_common_args: -o StrictHostKeyChecking=no

    # Wait for Embedded Rest Proxy to start - takes too long time
    kafka_broker_rest_proxy_enabled: false
zookeeper:
  hosts:
    zookeeper-qszdgrsh.westeurope.cloudapp.azure.com:
kafka_broker:
  hosts:
    kafka-0-qszdgrsh.westeurope.cloudapp.azure.com:
    kafka-1-qszdgrsh.westeurope.cloudapp.azure.com:
    kafka-2-qszdgrsh.westeurope.cloudapp.azure.com:
#schema_registry:
#  hosts:
#    platform-components-dpwolbsf.westeurope.cloudapp.azure.com:
#ksql:
#  hosts:
#    platform-components-dpwolbsf.westeurope.cloudapp.azure.com:
#kafka_connect:
#  hosts:
#    platform-components-dpwolbsf.westeurope.cloudapp.azure.com:
#      vars:
#        kafka_connect_confluent_hub_plugins:
#          - confluentinc/kafka-connect-datagen:0.4.0
#control_center:
#  hosts:
#    control-center-dpwolbsf.westeurope.cloudapp.azure.com: